name: Run Coverity scan and upload results

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'    # monthly


jobs:
  coverity-scan:
    uses: wultra/wultra-infrastructure/.github/workflows/coverity-scan.yml@develop
    secrets: inherit
    with:
      # for the legacy reason, the project name contains 'lime' at https://scan.coverity.com/projects/wultra-lime-java-core
      project-name: lime-java-core
      version: ${{ github.sha }}
      description: ${{ github.ref }}
